- type: entity
  abstract: true
  parent: [ FoodInjectableBase, OH14_BaseItem ]
  id: OH14_BasicFoodMeal
  description: A delicious meal, cooked with love.
  components:
  - type: Appearance
  - type: InworldSprite
  - type: GenericVisualizer
    visuals:
      enum.InworldSpriteState.State:
        base:
          True: {state: icon}
          False: {state: icon_inworld}
  - type: Item
    size: Tiny
  # - type: Sprite
  #   sprite: Objects/Consumable/Food/meals.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 31
        reagents:
        - ReagentId: Nutriment
          Quantity: 25

# ----------- Картошка

- type: entity
  name: картофель
  parent: OH14_BasicFoodMeal
  id: OH14_FoodPotato
  description: Съедобная кроха, посреди бесконечной пустоты.
  components:
  - type: Perishable
    rotAfter: 1800
    molsPerSecondPerUnitMass: 0
  - type: RotInto
    entity: OH14_FoodPotatoRotten
    stage: 1
  - type: FlavorProfile
    flavors:
      - potatoes
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: _OuterHorizons/Objects/Consumable/Food/potato.rsi
    layers:
      - state: icon_inworld
        map: ["base"]
  - type: Item
    size: Tiny
    # heldPrefix: produce
  - type: Produce
    seedId: OH14_Potato
  - type: Seed
    seedId: OH14_Potato
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuicePotato
        Quantity: 10
  - type: Tag
    tags:
    - Potato
    - Vegetable
  - type: FoodSequenceElement
    entries:
      Burger: Potato
      Taco: Potato

- type: entity
  name: гнилой картофель
  parent: [ FoodProduceBase, OH14_BaseItem ]
  id: OH14_FoodPotatoRotten
  components:
  - type: Appearance
  - type: InworldSprite
  - type: GenericVisualizer
    visuals:
      enum.InworldSpriteState.State:
        base:
          True: {state: icon}
          False: {state: icon_inworld}
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: GastroToxin
          Quantity: 10
        - ReagentId: Nutriment
          Quantity: 4
  - type: Sprite
    sprite: _OuterHorizons/Objects/Consumable/Food/potato.rsi
    layers:
      - state: icon_inworld
        map: ["base"]
        color: "#ABC4BA"
  - type: Item
    size: Tiny
  - type: Tag
    tags:
    - Potato
    - Vegetable

- type: entity
  parent: OH14_BasicFoodMeal
  id: OH14_FoodPotatoLoaded
  name: приготовленный картофель
  description: ВОТ ЭТО ЯВНО ЛУЧШЕ, ЧЕМ ЕБУЧАЯ ПИТАТЕЛЬНАЯ ПАСТА.
  components:
  - type: GenericVisualizer
    visuals:
      enum.InworldSpriteState.State:
        base:
          True: {state: icon_cooked}
          False: {state: icon_cooked_inworld}
  - type: Perishable
    rotAfter: 300
    molsPerSecondPerUnitMass: 0
  - type: RotInto
    entity: OH14_FoodPotato
    stage: 0
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - cheesy
      - potatoes
  - type: Sprite
    sprite: _OuterHorizons/Objects/Consumable/Food/potato.rsi
    layers:
      - state: icon_cooked_inworld
        map: ["base"]
