- type: construction
  hide: false
  id: OH14_HydroPot
  graph: OH14_HydroPot
  startNode: start
  targetNode: OH14_PlantPotEmpty
  category: construction-category-hydroponic
  objectType: Structure
  placementMode: SnapgridCenter
  canRotate: false
  canBuildInImpassable: false
