- type: job
  id: OH14_UcoRole
  name: Колонист
  description: Колонист, в бывшем на контракте с United Colonial Organization.
  playTimeTracker: OH14_UcoRole
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  setPreference: true
  startingGear: OH14_UcoGear
  access:
  - UCO

- type: startingGear
  id: OH14_UcoGear
  equipment:
    belt: OH14_ClothingBeltWaistbag
    outerClothing: OH14_ClothingOuterCoatUco
    jumpsuit: OH14_ClothingJumpsuitUco
    pants: OH14_ClothingPantsBasic
    back: ClothingBackpackSatchelUco
    shoes: OH14_ClothingBoots
    id: OH14_PDA
    pocket2: OH14_ClothingMaskGas
  # storage:
  #   tailbag:
  #   - OH14_CrowbarBasic

- type: playTimeTracker
  id: OH14_UcoRole
